apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: codeproject-ai-server
  namespace: default  # O cambia el namespace si prefieres otro
spec:
  releaseName: codeproject-ai-server
  interval: 59m0s
  chart:
    spec:
      chart: codeproject-ai-server  # Nombre del chart en TrueCharts
      sourceRef:
        kind: HelmRepository
        name: codeproject-ai-server
      #version: "x.x.x"  # Cambia esto si quieres una versión específica
  valuesFrom:
    - kind: ConfigMap
      name: codeproject-ai-server-values