apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-ai
  namespace: default  # O cambia el namespace si prefieres otro
spec:
  releaseName: local-ai
  interval: 59m0s
  chart:
    spec:
      chart: local-ai  # Nombre del chart en TrueCharts
      sourceRef:
        kind: HelmRepository
        name: truecharts  # Nombre del HelmRepository creado
        namespace: flux-system  # Namespace donde se encuentra el HelmRepository
      #version: "x.x.x"  # Cambia esto si quieres una versión específica
  valuesFrom:
    - kind: ConfigMap
      name: local-ai-values